# -*- coding: utf-8 -*-
"""Neptune_fastAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fO1IibirZClaBZZGcGxMj9yXDhIaBZDc
"""

import fastai
import neptune.new as neptune
from fastai.vision.all import *
from neptune.new.integrations.fastai import NeptuneCallback
run = neptune.init(
    project="dk-1232/NeptunefastAI",
    api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIxYmY5MGFiNC05OTQ1LTQ3YTAtODU3Ni0xMzU4NmYwZjY5ZTgifQ==",
)

path = untar_data(URLs.MNIST_TINY)

path.ls()

dls = ImageDataLoaders.from_csv(path, bs = 128)

dls.show_batch()
learn = cnn_learner(dls, resnet34, cbs=[NeptuneCallback(run,"experiment"), SaveModelCallback()])

learn.fit_one_cycle(100)

run.stop()
