# -*- coding: utf-8 -*-
"""Weights & Biases with fastai

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CehpvGSICuqlsIVB5zh5xr-4g_rHe14K

## 1- Install libraries

First, install and import `fastai` and `wandb`.
"""

!pip install -qqq wandb
!pip install -qqqU fastai

from fastai.vision.all import *
import wandb
from fastai.callback.wandb import *

"""## 2- Log in to W&B
Log in so your results can stream to a private project in W&B. Here's more info on the [data privacy and export features](https://docs.wandb.com/company/data-and-privacy) you can use so W&B can serve as a reliable system of record for your experiments.

*Note: Login only needs to be done once, and it is automatically called with `wandb.init()`.*
"""

wandb.login()

"""## 3- Download the dataset

Fastai datasets are downloaded from a URL and cached locally.
"""

path = untar_data(URLs.MNIST_TINY)
path

"""This specific dataset contains:
* a folder of input images
* a folder of segmentation masks (same name as images with added suffix `_P`)
* a file listing in order the possible classes
* a file listing which files belong to validation set

## 4- Create DataLoaders
We can create `DataLoaders` in many possible ways: from a `Dataset`, `TfmdList`, `DataBlock` or custom methods such as `ImageDataLoaders` or `SegmentationDataLoaders`.
"""

dls = ImageDataLoaders.from_csv(path,bs=128)
dls.show_batch()

"""## 5- Train a model

We start a new W&B run with wandb.init() which gives us a link to our logged run.
"""

wandb.init(project='fastai');

"""`WandbCallback` can automatically track:
* hyper-parameters
* losses & metrics
* models
* datasets
* code
* computer resources

In addition to logging losses & metrics, we are going to log our dataset and our model, which will be automatically versioned.
"""

learn = cnn_learner(dls, resnet34, cbs=[WandbCallback(log_dataset=True, log_model=True), SaveModelCallback()])

learn.fit_one_cycle(100)

# optional: mark the run as completed
wandb.finish()

"""That's it! Check out your fastai model training in the live W&B dashboard by clicking on the link printed out above.

# Example W&B dashboard
![](https://i.imgur.com/jef6GjA.png)

"""